import { getAuthSession, normalizeSupabaseError, supabase, type NormalizedSupabaseError } from "../../lib/supabase";
import { resolveAccountDeletionEndpoint } from "./accountDeletionEndpoint";

type PrivacyActionResult<T> = {
  data: T | null;
  error: NormalizedSupabaseError | null;
};

type ExportedUserData = {
  exported_at: string;
  user_id: string;
  profile: unknown;
  preferences: unknown;
  newsletter_topic_preferences: unknown[];
  mini_case_topic_preferences: unknown[];
  content_interactions: unknown[];
  mini_case_responses: unknown[];
  push_tokens: unknown[];
  daily_drops: unknown[];
  team_memberships: unknown[];
  question_attempts: unknown[];
  team_edition_scores: unknown[];
  user_blocks: unknown[];
  user_reports: unknown[];
};

const accountDeletionEndpoint = resolveAccountDeletionEndpoint(
  process.env.EXPO_PUBLIC_ACCOUNT_DELETION_ENDPOINT,
  process.env.EXPO_PUBLIC_SUPABASE_URL
);

export async function exportAuthenticatedUserData(
  userId: string
): Promise<PrivacyActionResult<string>> {
  if (!supabase) {
    return {
      data: null,
      error: {
        code: "missing_supabase_config",
        message: "Live account data is not configured for this build."
      }
    };
  }

  try {
    const [
      profile,
      preferences,
      newsletterTopics,
      miniCaseTopics,
      interactions,
      miniCaseResponses,
      pushTokens,
      dailyDrops,
      teamMemberships,
      questionAttempts,
      teamEditionScores,
      blocks,
      reports
    ] = await Promise.all([
      // The Teams identity columns belong here as much as the email does:
      // `username` is a name the reader chose, `country_code` a declaration
      // they made about themselves, and `avatar_path` names a photograph of
      // them. An export that omitted them would be describing a smaller
      // account than the one that exists.
      //
      // `avatar_path` is the object path, not a signed URL — the same value the
      // row stores. A URL in an export file expires and turns a data export
      // into a broken link.
      supabase
        .from("profiles")
        .select(
          "id,email,legacy_user_id,language,timezone,username,country_code,avatar_path,username_status,avatar_status,created_at,updated_at"
        )
        .eq("id", userId)
        .maybeSingle(),
      supabase.from("user_preferences").select("*").eq("user_id", userId).maybeSingle(),
      supabase
        .from("user_topic_preferences")
        .select("*")
        .eq("user_id", userId)
        .order("position", { ascending: true, nullsFirst: false }),
      supabase
        .from("user_mini_case_topic_preferences")
        .select("*")
        .eq("user_id", userId)
        .order("position", { ascending: true, nullsFirst: false }),
      supabase
        .from("content_interactions")
        .select("*")
        .eq("user_id", userId)
        .order("created_at", { ascending: false }),
      supabase
        .from("mini_case_responses")
        .select("*")
        .eq("user_id", userId)
        .order("created_at", { ascending: false }),
      supabase
        .from("push_tokens")
        .select("id,user_id,expo_push_token,platform,enabled,last_registered_at,created_at,updated_at")
        .eq("user_id", userId)
        .order("created_at", { ascending: false }),
      supabase
        .from("daily_drops")
        .select("id,user_id,drop_date,language,status,generated_at,published_at,created_at,updated_at")
        .eq("user_id", userId)
        .order("drop_date", { ascending: false }),
      // Teams. Personal data the reader generated by playing, so it belongs in
      // an export exactly as their reading history does.
      //
      // Note what is NOT exported: nothing from `private.logical_question_grades`
      // and no rationale. Those are editorial material about a question, not
      // personal data about the reader, and a data export must not become the
      // way the answer key leaves the server.
      supabase
        .from("team_members")
        .select("team_id,role,joined_at,left_at,eligible_from_edition")
        .eq("user_id", userId)
        .order("joined_at", { ascending: false }),
      supabase
        .from("question_attempts")
        .select("id,logical_question_id,edition_date,started_at,deadline_at,submitted_at,selected_option_id,score_milli,status")
        .eq("user_id", userId)
        .order("started_at", { ascending: false }),
      supabase
        .from("team_member_edition_scores")
        .select("team_id,edition_date,score_milli,answered_count,assigned_count,completed,updated_at")
        .eq("user_id", userId)
        .order("edition_date", { ascending: false }),
      supabase
        .from("user_blocks")
        .select("blocked_id,created_at")
        .eq("blocker_id", userId),
      // The reader's own reports. Reports ABOUT them are deliberately absent:
      // exposing who reported you is how a report system becomes a way to
      // retaliate.
      supabase
        .from("user_reports")
        .select("id,reported_user_id,team_id,reason,details,status,created_at")
        .eq("reporter_id", userId)
        .order("created_at", { ascending: false })
    ]);

    const firstError =
      profile.error ??
      preferences.error ??
      newsletterTopics.error ??
      miniCaseTopics.error ??
      interactions.error ??
      miniCaseResponses.error ??
      pushTokens.error ??
      dailyDrops.error ??
      teamMemberships.error ??
      questionAttempts.error ??
      teamEditionScores.error ??
      blocks.error ??
      reports.error;

    if (firstError) {
      return {
        data: null,
        error: normalizeSupabaseError(firstError, "Could not export your account data.")
      };
    }

    const exportPayload: ExportedUserData = {
      exported_at: new Date().toISOString(),
      user_id: userId,
      profile: profile.data,
      preferences: preferences.data,
      newsletter_topic_preferences: newsletterTopics.data ?? [],
      mini_case_topic_preferences: miniCaseTopics.data ?? [],
      content_interactions: interactions.data ?? [],
      mini_case_responses: miniCaseResponses.data ?? [],
      push_tokens: pushTokens.data ?? [],
      daily_drops: dailyDrops.data ?? [],
      team_memberships: teamMemberships.data ?? [],
      question_attempts: questionAttempts.data ?? [],
      team_edition_scores: teamEditionScores.data ?? [],
      user_blocks: blocks.data ?? [],
      user_reports: reports.data ?? []
    };

    return {
      data: JSON.stringify(exportPayload, null, 2),
      error: null
    };
  } catch (error) {
    return {
      data: null,
      error: normalizeSupabaseError(error, "Could not export your account data.")
    };
  }
}

/**
 * Delete the signed-in account, for good.
 *
 * The caller's identity is carried by the access token and by nothing else: no
 * user id is sent, because the endpoint would ignore it anyway. That is the
 * property that makes this safe to expose — a request can only ever delete the
 * account whose token signed it.
 *
 * The `userId` argument is kept for the caller's own guard (there must be a
 * signed-in user to delete) and is deliberately never transmitted.
 */
export async function requestAuthenticatedAccountDeletion(
  userId: string
): Promise<PrivacyActionResult<{ requested: true }>> {
  if (!accountDeletionEndpoint) {
    return {
      data: null,
      error: {
        code: "account_deletion_endpoint_missing",
        message:
          "Account deletion requests are not enabled in this build. Contact the PersoNewsAP operator through the official support channel."
      }
    };
  }

  const sessionResult = await getAuthSession();

  if (!userId || sessionResult.error || !sessionResult.data) {
    return {
      data: null,
      error:
        sessionResult.error ??
        ({
          code: "missing_auth_session",
          message: "Log in again before requesting account deletion."
        } satisfies NormalizedSupabaseError)
    };
  }

  try {
    const response = await fetch(accountDeletionEndpoint, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${sessionResult.data.access_token}`,
        "Content-Type": "application/json"
      },
      // Empty body on purpose: the server derives the account from the JWT.
      body: JSON.stringify({})
    });

    if (!response.ok) {
      // The account is untouched on any non-2xx: the caller keeps its session
      // and can retry.
      return {
        data: null,
        error: {
          code:
            response.status === 401
              ? "account_deletion_unauthorized"
              : "account_deletion_request_failed",
          message:
            response.status === 401
              ? "Log in again, then retry the deletion."
              : "Your account was not deleted. Please try again.",
          status: response.status
        }
      };
    }

    return {
      data: { requested: true },
      error: null
    };
  } catch (error) {
    return {
      data: null,
      error: normalizeSupabaseError(error, "Your account was not deleted. Please try again.")
    };
  }
}
