import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  avatarObjectPath,
  canWriteAvatarPath,
  isStorablePath,
  ownerOfAvatarPath,
  stripBucketPrefix
} from "../teams/avatarPolicy";

/**
 * The privacy half of the security pass: what leaves the account, and what is
 * left behind when the account does.
 *
 * Two of these are source assertions rather than behavioural ones, for the
 * usual reason — the export talks to Supabase and the deletion endpoint runs in
 * Deno — and both pin a decision that is invisible until somebody exercises
 * their rights and finds the answer wrong.
 */

const root = join(__dirname, "..", "..", "..", "..", "..");
const stripComments = (source: string) =>
  source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");

const exporter = stripComments(readFileSync(join(__dirname, "privacyData.ts"), "utf8"));
const deleteAccount = stripComments(
  readFileSync(join(root, "supabase", "functions", "delete-account", "index.ts"), "utf8")
);
const form = stripComments(
  readFileSync(join(root, "apps", "mobile", "src", "features", "teams", "PlayerProfileForm.tsx"), "utf8")
);
const upload = stripComments(
  readFileSync(join(root, "apps", "mobile", "src", "features", "teams", "avatarUpload.ts"), "utf8")
);

const profileSelect = /\.from\("profiles"\)\s*\.select\(\s*\n?\s*"([^"]+)"/.exec(exporter)?.[1] ?? "";

describe("the export describes the whole account", () => {
  it("finds the profile select at all", () => {
    // Guards the assertions below: a refactor that changed the call shape would
    // otherwise turn every one of them into a vacuous pass.
    expect(profileSelect.length).toBeGreaterThan(0);
  });

  it("includes the identity the reader chose for Teams", () => {
    for (const column of ["username", "country_code", "avatar_path"]) {
      expect(profileSelect.split(","), column).toContain(column);
    }
  });

  it("includes the moderation flags standing against them", () => {
    // A reader is entitled to know their name has been hidden. Omitting it
    // would make the export a friendlier account than the real one.
    expect(profileSelect).toContain("username_status");
    expect(profileSelect).toContain("avatar_status");
  });

  it("exports the Teams data the reader generated by playing", () => {
    for (const table of [
      "team_members",
      "question_attempts",
      "team_member_edition_scores",
      "user_blocks",
      "user_reports"
    ]) {
      expect(exporter, table).toContain(`.from("${table}")`);
    }
  });

  it("never exports the answer key", () => {
    // A data export must not become the way private grading leaves the server.
    expect(exporter).not.toMatch(/logical_question_grades/i);
    expect(exporter).not.toMatch(/option_feedback/i);
    expect(exporter).not.toMatch(/\bprivate\./i);
  });

  it("exports the reader's own reports and never the ones about them", () => {
    // Exposing who reported you is how a report system becomes retaliation.
    expect(exporter).toMatch(/from\("user_reports"\)[\s\S]{0,200}eq\("reporter_id", userId\)/);
    expect(exporter).not.toMatch(/eq\("reported_user_id", userId\)/);
  });

  it("exports a storage path, never a signed URL", () => {
    expect(exporter).not.toMatch(/createSignedUrl|getPublicUrl/i);
  });
});

describe("deleting an account takes the photograph with it", () => {
  it("reads the avatar before the row that names it is gone", () => {
    expect(deleteAccount).toMatch(/\.select\("legacy_user_id,avatar_path"\)/);
  });

  it("clears Storage before the auth user, not after", () => {
    const sweep = deleteAccount.indexOf("removeAvatarObjects(adminClient");
    const authDelete = deleteAccount.indexOf("auth.admin.deleteUser");

    expect(sweep).toBeGreaterThan(-1);
    expect(authDelete).toBeGreaterThan(-1);
    // After the delete there is no caller left to retry, and no row left to say
    // which object was orphaned.
    expect(sweep).toBeLessThan(authDelete);
  });

  it("fails the whole request when Storage refuses", () => {
    // The deliberate choice: a 200 must mean the personal data is actually
    // gone. Best-effort cleanup would make "deleted" a claim the server cannot
    // back up, and the account that could have retried would already be gone.
    expect(deleteAccount).toMatch(/avatar_cleanup_failed/);
    expect(deleteAccount).toMatch(
      /if \(!avatarRemoval\.ok\)[\s\S]{0,400}return jsonResponse\([\s\S]{0,300}500/
    );
  });

  it("sweeps the folder, so an interrupted replace leaves nothing", () => {
    expect(deleteAccount).toMatch(/bucket\.list\(userId/);
    expect(deleteAccount).toMatch(/offset \+= pageSize/);
  });

  it("treats an empty folder as success", () => {
    // A reader who never opened Teams has no avatar, and must still be able to
    // delete their account.
    expect(deleteAccount).toMatch(/names\.size === 0[\s\S]{0,80}ok: true/);
  });

  it("still never trusts the request body for identity", () => {
    expect(deleteAccount).toMatch(/callerClient\.auth\.getUser\(\)/);
    expect(deleteAccount).toMatch(/removeAvatarObjects\(adminClient, user\.id/);
  });
});

describe("replacing an avatar does not accumulate objects", () => {
  it("deletes the previous object after the profile write, never before", () => {
    const save = form.indexOf("await savePlayerIdentity(");
    const cleanup = form.indexOf("deleteAvatarObject(replaced)");

    expect(cleanup).toBeGreaterThan(-1);
    // Reversed, a failed profile write would delete the picture the reader
    // still has.
    expect(cleanup).toBeGreaterThan(save);
  });

  it("does not delete anything when the path did not change", () => {
    expect(form).toMatch(/replaced !== result\.data\.avatarPath/);
  });

  it("does not block the reader on it", () => {
    // Nothing they can see depends on the delete; the cost of a failure is one
    // orphan, which account deletion sweeps by folder.
    expect(form).toMatch(/void deleteAvatarObject/);
  });

  it("addresses the object without the bucket name", () => {
    expect(upload).toMatch(/stripBucketPrefix\(path\)/);
    expect(upload).toMatch(/from\("avatars"\)\.remove\(\[objectPath\]\)/);
  });
});

describe("the path rules the server now enforces too", () => {
  const me = "11111111-2222-4333-8444-555555555555";
  const victim = "99999999-8888-4777-8666-555555555555";

  it("builds a two-segment path owned by the writer", () => {
    const path = avatarObjectPath({ userId: me, fileId: "abc" });

    expect(path).toBe(`${me}/abc.jpg`);
    expect(ownerOfAvatarPath(path)).toBe(me);
    expect(canWriteAvatarPath({ path, userId: me })).toBe(true);
  });

  it("refuses to write into another reader's folder", () => {
    // The client half of the impersonation fix. The server half is
    // set_player_identity's is_own_avatar_path check, which is what actually
    // stops a rewritten binary.
    expect(canWriteAvatarPath({ path: `${victim}/photo.jpg`, userId: me })).toBe(false);
  });

  it("refuses a path that repeats the bucket name", () => {
    expect(canWriteAvatarPath({ path: `avatars/${me}/photo.jpg`, userId: me })).toBe(false);
  });

  it("still resolves a legacy prefixed path for reading", () => {
    expect(stripBucketPrefix(`avatars/${me}/photo.jpg`)).toBe(`${me}/photo.jpg`);
    expect(ownerOfAvatarPath(`avatars/${me}/photo.jpg`)).toBe(me);
  });

  it("never stores a URL", () => {
    expect(isStorablePath("https://example.test/signed?token=abc")).toBe(false);
    expect(isStorablePath(`${me}/photo.jpg`)).toBe(true);
  });

  it("refuses traversal", () => {
    expect(isStorablePath(`${me}/../${victim}/photo.jpg`)).toBe(false);
    expect(canWriteAvatarPath({ path: `${me}/../photo.jpg`, userId: me })).toBe(false);
  });
});
